//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Childrens_sanatorium.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Children
    {
        public int id_children { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public int id_diagnosis { get; set; }
        public int id_braches { get; set; }
        public int id_ward { get; set; }
        public string Comments { get; set; }
        public int id_emploee { get; set; }
        public byte[] Image { get; set; }
        public Nullable<System.DateTime> Date_of_receipt { get; set; }
    
        public virtual Branches Branches { get; set; }
        public virtual Diagnosis Diagnosis { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
