//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Childrens_sanatorium.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ward
    {
        public int id_ward { get; set; }
        public int ward_number { get; set; }
        public int id_branches { get; set; }
    
        public virtual Branches Branches { get; set; }
    }
}
